sudo: required
services:
  - docker

before-install:
  - docker build -t sirajalik/docker-react -f Dockerfile .

script:
  - docker run sirajalik/docker-react npm run test -- --coverage

 before_deploy: "echo 'ready?'" 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-969706004206"
  bucker_path: "docker-react"
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  on:
    branch: master

after_failure:
  - cat MSBuild_*.failure.txt