sudo: required
services:
  - docker

before-install:
  - docker build -t sirajalik/docker-react -f Dockerfile.dev .

script:
  - docker run sirajalik/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket-name: "elasticbeanstalk-us-east-1-969706004206"
  bucker-path: "docker-react"
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
